# Generated by Django 4.0.2 on 2022-02-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('sku_id', models.CharField(max_length=50, verbose_name='id товара')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('reviews_amount', models.IntegerField(verbose_name='Количество отзывов')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Автор комментария')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата отзыва')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pros', models.TextField(verbose_name='Плюсы')),
                ('cons', models.TextField(verbose_name='Минусы')),
                ('likes', models.IntegerField(verbose_name='Лайки')),
                ('dislikes', models.IntegerField(verbose_name='Дизлайки')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.product', verbose_name='Товар')),
            ],
        ),
    ]
