# Generated by Django 3.2.12 on 2022-02-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, null=True, verbose_name='Минусы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, null=True, verbose_name='Плюсы'),
        ),
    ]
